In [ ]:
from keras.layers import Embedding
from keras.models import Sequential
from keras.datasets import imdb
import keras as K
import numpy as np

max_words = 20000

(train_x, train_y), (test_x, test_y) = imdb.load_data(num_words=max_words)

max_review_length = 80
train_x = K.preprocessing.sequence.pad_sequences(train_x, truncating='pre', padding='pre', maxlen=max_review_length)
test_x = K.preprocessing.sequence.pad_sequences(test_x, truncating='pre', padding='pre', maxlen=max_review_length)


<string>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
/usr/local/lib/python3.7/dist-packages/keras/datasets/imdb.py:155: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_train, y_train = np.array(xs[:idx]), np.array(labels[:idx])
/usr/local/lib/python3.7/dist-packages/keras/datasets/imdb.py:156: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the nda

In [ ]:
model = Sequential()
embedding_length = 5
max_words = 1000
max_sentence_length = 10
model.add(Embedding(max_words, embedding_length, input_length=max_sentence_length))

In [ ]:
input_array = input_array = np.random.randint(max_words, size=(2, max_sentence_length)) #train_x[0]
print(input_array, np.shape(input_array))

[[440 467 939  55  56 958  93 210 581 529]
 [385 386 195 793 320 744  21 521 268 869]] (2, 10)


In [ ]:
model.compile('rmsprop', 'mse')
output_array = model.predict(input_array)
#assert output_array.shape == (32, 10, 64)
print(output_array, np.shape(output_array))

[[[ 0.00823079  0.01248496 -0.01646018 -0.00269481 -0.01108527]
  [ 0.04698429 -0.03933779 -0.04472926  0.01845967  0.00827593]
  [-0.04515139 -0.03818123  0.04845938  0.00667255 -0.03044527]
  [ 0.03008166  0.01625464 -0.01174265 -0.04172384 -0.02997736]
  [ 0.03684118  0.04618182  0.02372007  0.03597099 -0.02333273]
  [ 0.02102147  0.00428706 -0.0107574  -0.00835482 -0.00716909]
  [ 0.04993251 -0.0029865  -0.00903111  0.03496924 -0.03935234]
  [ 0.01276711 -0.02012783  0.02698398  0.04381147  0.01707866]
  [-0.01636467 -0.03177331 -0.0375899  -0.00515259  0.04458929]
  [ 0.04989732  0.03432142  0.01087135 -0.01380199 -0.00982915]]

 [[ 0.02176341  0.046186   -0.03126267  0.01847743  0.04988084]
  [-0.04030739 -0.01701448 -0.04043832  0.00448008  0.00922952]
  [ 0.00436815 -0.01289821  0.01689685 -0.03417309 -0.01270777]
  [-0.0284971   0.01244831 -0.02068236 -0.03370514 -0.00427203]
  [-0.00789305 -0.02827104 -0.03708944  0.0493309  -0.04429071]
  [-0.03909666 -0.03976964  0.02762625

In [ ]:
"""# One hot representation"""

from keras.preprocessing.text import one_hot

#define documents
docs = ['glass of orange juice',
        'bottle of mango juice',
        'glass of mango shake',
        'drink bottle of banana shake',
        'I want a glass of cold water',
        'The king and the queen',
        'man and woman']

vocab_size = 10000

encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[5668, 8828, 7301, 9960], [9677, 8828, 5248, 9960], [5668, 8828, 5248, 3949], [4491, 9677, 8828, 7681, 3949], [7322, 3784, 3330, 5668, 8828, 2297, 14], [4991, 8632, 5318, 4991, 6258], [1173, 5318, 8891]]


In [ ]:
"""# Word Embeddings"""

from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Embedding, LSTM

import numpy as np

embedding_length = 5
max_doc_len = 10

encoded_docs = pad_sequences(encoded_docs, truncating='post', padding='post', maxlen=max_doc_len)

print(encoded_docs)

model = Sequential()

model.add(Embedding(vocab_size, embedding_length, input_length=max_doc_len))
model.add(LSTM(units=64))

model.compile('rmsprop', 'mse')

model.summary()

output = model.predict(encoded_docs)
print(output.shape)
print(output)


[[5668 8828 7301 9960    0    0    0    0    0    0]
 [9677 8828 5248 9960    0    0    0    0    0    0]
 [5668 8828 5248 3949    0    0    0    0    0    0]
 [4491 9677 8828 7681 3949    0    0    0    0    0]
 [7322 3784 3330 5668 8828 2297   14    0    0    0]
 [4991 8632 5318 4991 6258    0    0    0    0    0]
 [1173 5318 8891    0    0    0    0    0    0    0]]
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 10, 5)             50000     
_________________________________________________________________
lstm (LSTM)                  (None, 64)                17920     
Total params: 67,920
Trainable params: 67,920
Non-trainable params: 0
_________________________________________________________________
(7, 64)
[[-3.93238151e-03 -3.78084928e-03 -3.21151270e-03 -6.02317508e-04
  -3.23992991e-03  2.66992254e-04  8.00447632e-03 -1.51037599e-03


In [ ]:
"""##Putting it together
#Sentiment Analysis in Keras

Import libraries and dataset
"""

import keras
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.layers import LSTM
from keras.datasets import imdb

max_words = 20000
print('Loading data...')
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=max_words)
print(len(x_train), 'train sequences')
print(len(x_test), 'test sequences')

Loading data...


<string>:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
/usr/local/lib/python3.7/dist-packages/keras/datasets/imdb.py:155: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_train, y_train = np.array(xs[:idx]), np.array(labels[:idx])


25000 train sequences
25000 test sequences


/usr/local/lib/python3.7/dist-packages/keras/datasets/imdb.py:156: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_test, y_test = np.array(xs[idx:]), np.array(labels[idx:])


In [ ]:
"""Pre-processing"""

# cut texts after this number of words (among top max_features most common words)
max_review_length = 80

x_train = sequence.pad_sequences(x_train, truncating='pre', padding='pre', maxlen=max_review_length)
x_test = sequence.pad_sequences(x_test, truncating='pre', padding='pre', maxlen=max_review_length)

print('x_train shape:', x_train.shape)
print('x_test shape:', x_test.shape)



x_train shape: (25000, 80)
x_test shape: (25000, 80)


In [ ]:
"""Build the model"""

print('Build model...')
embedding_length = 64
model = Sequential()
model.add(Embedding(input_dim=max_words, output_dim=embedding_length, input_length=max_review_length))
model.add(LSTM(units=64, input_shape=(max_review_length, embedding_length), return_sequences=True, unroll=True))
model.add(LSTM(units=32))
model.add(Dense(1, activation='sigmoid'))

# try using different optimizers and different optimizer configs
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

Build model...


In [ ]:
"""Visualize the model"""

#Visualize
model.summary()


Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 80, 64)            1280000   
_________________________________________________________________
lstm_1 (LSTM)                (None, 80, 64)            33024     
_________________________________________________________________
lstm_2 (LSTM)                (None, 32)                12416     
_________________________________________________________________
dense (Dense)                (None, 1)                 33        
Total params: 1,325,473
Trainable params: 1,325,473
Non-trainable params: 0
_________________________________________________________________


In [ ]:
"""Train the model"""

print('Training...')
batch_size = 32

model.fit(x_train, y_train,
          batch_size = batch_size,
          epochs=5,
          validation_data = (x_test, y_test))

Training...
Epoch 1/5
782/782 [==============================] - 130s 113ms/step - loss: 0.5052 - accuracy: 0.7303 - val_loss: 0.3787 - val_accuracy: 0.8322
Epoch 2/5
782/782 [==============================] - 78s 100ms/step - loss: 0.2339 - accuracy: 0.9108 - val_loss: 0.3781 - val_accuracy: 0.8344
Epoch 3/5
782/782 [==============================] - 78s 100ms/step - loss: 0.1388 - accuracy: 0.9506 - val_loss: 0.4760 - val_accuracy: 0.8218
Epoch 4/5
782/782 [==============================] - 78s 99ms/step - loss: 0.0814 - accuracy: 0.9715 - val_loss: 0.6053 - val_accuracy: 0.8185
Epoch 5/5
782/782 [==============================] - 78s 100ms/step - loss: 0.0513 - accuracy: 0.9840 - val_loss: 0.6866 - val_accuracy: 0.8136


In [ ]:
"""Evaluate the model"""

score, acc = model.evaluate(x_test, y_test, batch_size=batch_size)
print(f'Test score = {score}')
print(f'Test accuracy = {acc}')

782/782 [==============================] - 17s 21ms/step - loss: 0.6866 - accuracy: 0.8136
Test score = 0.6865746974945068
Test accuracy = 0.8135600090026855


In [ ]:
""" Making predicitions with model """
review = "The movie was super cool"

print(f"New review = {review} ")

d= imdb.get_word_index()
words = review.split()
review = []

for word in words:
  word = word.lower()
  if word not in d:
    review.append(2)
  else:
    review.append(d[word] + 3)

print(f"review = {review}")

review = sequence.pad_sequences([review], truncating='pre', padding='pre', maxlen=80)

prediction = model.predict(review)

print(f'Prediction (0= Negative, 1 = positive) = {prediction}')



New review = The movie was super cool 
review = [4, 20, 16, 1165, 646]
Prediction (0= Negative, 1 = positive) = [[0.86981547]]
